name: Build, test, commit and deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-optional

      # Build widget assets and templates.
      - name: Build assets (for Github Pages deployment)
        run: npm run build

      - name: Upload Github Pages build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: public/**
          retention-days: 1

  # Prepare the "dist" directory use by GitHub pages to serve compiled widget assets.
  bundle:
    name: Bundle and Commit
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy assets from "Build" step into "dist/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: dist/

      # Debugging step to display ./dist directory contents in GitHub action logs.
      - name: Display structure of downloaded files
        run: ls -l
        working-directory: dist/

      # Commit any changes to ./dist directory..
      - name: Commit bundled dist changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Github Actions] - Bundled assets for build number: ${{ github.run_number }}"

  # Runs the release job if we're on "main" branch to deploy our latest build to GitHub Pages.
  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    needs: [bundle]
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      #  Ensures that we use the latest commit from step: "Commit bundled dist changes" above.
      - name: Fetch latest commit from bundle step
        run: git pull --no-rebase

      # Deploys and updates GitHub Pages.
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
