name: Build, test, commit and deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout hee-prototypes repo (Enhancement/NWPS-1671-nhse-POC-visual-identity)
        uses: actions/checkout@v4
        with:
          repository: Health-Education-England/hee-prototypes
          path: hee-prototypes
          ref: Enhancement/NWPS-1671-nhse-POC-visual-identity

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install widget dependencies
        run: npm install --no-optional

      - name: Configure environment variables
        run: cp -f .github/config/prod.env ./.env

      # Build widget assets and templates.
      - name: Build widget assets
        run: npm run build

      - name: Upload Github Pages build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: widget-assets
          path: public/widgets/global-menu/**
          retention-days: 1

      # Build HEE prototype assets and templates.
      - name: Install hee-prototypes dependencies
        run: npm install --no-optional --prefix hee-prototypes

      - name: Build hee-prototypes assets
        run: npm run build:staging --prefix hee-prototypes

      - name: Merge hee-prototypes assets into public folder
        run: cp -r hee-prototypes/public/. public/

      - name: Upload Github Pages build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: public/**
          retention-days: 1

  # Prepare and commit "dist" directory (only widget related assets)
  bundle:
    name: Bundle and Commit
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy assets from "Build" step into "dist/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: widget-assets
          path: dist/

      # Debugging step to display ./dist directory contents in GitHub action logs.
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist/

      # Commit any changes to ./dist directory..
      - name: Commit bundled dist changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Github Actions] - Bundled assets for build number: ${{ github.run_number }}"

  # Runs the release job if we're on "main" branch to deploy our latest build to GitHub Pages.
  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      # Checkout repo from GitHub and use current branch.
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy assets from "Build" step into "dist/" directory.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: public/

      # Deploys and updates GitHub Pages.
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: public
